name: notaps_study_enjp_corporate
description: notaps - English learning app with subscription model
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  wakelock_plus: ^1.1.1
  url_launcher: ^6.3.1
  flutter_tts: ^3.8.2
  sensors_plus: ^4.0.1
  google_fonts: ^6.1.0
  in_app_review: ^2.0.9
  in_app_purchase: ^3.1.13


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/word_finalized_0613.json
    - assets/icon/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/appicon1024.png"
  remove_alpha_ios: true